### PR TITLE
feat: add incidentio provider

### LINKED ISSUE #1259: [🔌 Provider] Incident.IO
**Describe the provider you want to add**
Provider for https://incident.io/

**Describe your use case**
I would love this provider to query all incidents, including metadata (participants, timeline, some other info?) as an event into Keep.

**Are you already using Keep?**
Yes/No

**Additional context**
This provider needs to fetch all incidents from the 3rd party retrospectively.

### PR DESCRIPTION
**Pull request by 35C4n0r**
Closes #1259
/claim #1259

/split @ezhil56x 

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by Matvey-Kuk** [comment]
@35C4n0r I asked Incident.io team for the environment with the pro subscription to test this <3

**Comment by Matvey-Kuk** [comment]
So far:  Screenshot 2024-07-10 at 17 27 46

**Comment by ezhil56x** [comment]
@Matvey-Kuk On it, will get it done by tomorrow

**Comment by talboren** [comment]
@ezhil56x any news about this one?

**Comment by talboren** [comment]
@35C4n0r @Matvey-Kuk is this still relevant? can we close it?

**Comment by 35C4n0r** [comment]
@talboren fixed everything, we are good to go.
image

**Review by Matvey-Kuk — APPROVED** [review]

**Pull request merged**
