### PR TITLE
fix(providers): Make PagerDuty provider to fetch incidents retrospectively (#1262)

### LINKED ISSUE #1262: [🔌 Provider] Make PagerDuty provider to fetch incidents retrospectively
**Is your feature request related to a problem? Please describe.**
PagerDuty provider in fetching new Incidents that happened only after it was connected: 
Screenshot 2024-06-20 at 18 40 39

Fetched payload is also pretty limited:
```
{
  "environment": "unknown",
  "service": "Default Service",
  "apiKeyRef": null,
  "message": null,
  "labels": {},
  "fingerprint": "ea614d4639cd2ca3e5857adc6189b26b1a73b45858605ed64045615e4d8f6429",
  "dismissUntil": null,
  "dismissed": false,
  "startedAt": "2024-06-20 15:39:30.550000",
  "isNoisy": false,
  "priority": null,
  "escalation_policy": {
    "id": "PPB6DK3",
    "self": "https://api.pagerduty.com/escalation_policies/PPB6DK3",
    "type": "escalation_policy_reference",
    "summary": "Default",
    "html_url": "https://asdlksa.pagerduty.com/escalation_policies/PPB6DK3"
  },
  "number": 2,
  "type": "incident",
  "resolve_reason": null,
  "alert_hash": "15d56631ceea5f7559ba83041f3768227dbc20dde60dffa1eecb9226fe38dd68",
  "urgency": "high",
  "teams": [],
  "conference_bridge": null,
  "incident_key": "4c7286b70d4946ddaccb2b9cd8de824b"
}
```

**Describe the solution you'd like**
1. We would love to see all past incidents also being fetched.
2. Important metadata, such as impacted services, notes, etc, should also be fetched to the event metadata.

It will help to query and analyze PD incidents inside Keep.

### PR DESCRIPTION
**Pull request by mobley-trent**
Closes #1262
/claim #1262

## 📑 Description

- Improves fetch payload
- Allows Pagerduty provider to fetch alerts that happened before connecting to Keep

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by mobley-trent** [comment]
Hi @Matvey-Kuk the Keep instance running on localhost is returning the first critical event triggered when I created the Pagerduty demo account. This is before I connected to Keep on the localhost development version. The live version of Keep does not show the alert though. Any advice on how to debug this ?

Dev version:
Screenshot 2024-06-21 125511



Live version:
Screenshot 2024-06-21 125822

**Comment by mobley-trent** [comment]
Update: Both versions of Keep are showing the all the events, including the event created before connecting Pagerduty to Keep. Unless I did not understand the issue fully, is this just a bug on your end ?

Screenshot 2024-06-21 174348
Screenshot 2024-06-21 174403

**Comment by Matvey-Kuk** [comment]
@mobley-trent sorry for the late reply. You are right, the pulling feature is outside of the scope of this PR. So let's focus on bringing as much metadata as possible :)

**Comment by mobley-trent** [comment]
Hi @Matvey-Kuk I squeezed out most of the metadata from the response payload sent from the Pagerduty API, while avoiding data duplication. I added a simple unit test that utilizes a response payload I received as the data.

**Review by Matvey-Kuk — APPROVED** [review]

**Comment by mobley-trent** [comment]
@Matvey-Kuk kindly approve the bounty 🙏

**Comment by Matvey-Kuk** [comment]
@mobley-trent of course!

**Comment by mobley-trent** [comment]
Hello @Matvey-Kuk 👋 unfortunately I am yet to receive the bounty

**Pull request merged**
