### PR TITLE
fix: Validates New Relic provider api url has https #1152

### LINKED ISSUE #1152: new relic validate the api URL is valid URL (starts with https)

### PR DESCRIPTION
**Pull request by KanvaBhatia**
Closes #1152

## 📑 Description

Added a validation that the api url starts with 'https' in `validate_config` of `NewrelicProvider`.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

Old behaviour - 
Earlier it used to show this error instead of validating url.
image

New - 
Added `https` validation in the config, hence this meaningful `error_msg`.
image

- I am not sure if this is the expected fix.

Thanks

### CODE REVIEW

**Review by talboren — CHANGES_REQUESTED** [review]
@KanvaBhatia I think we should adjust frontend to accept different errors (not only scope validation) from the backend to display the error message you return from the URL validation properly. Are you up for fixing that too?

**Comment by talboren** [comment]
@KanvaBhatia sounds perfect! Looking forward to reviewing this change

**Comment by KanvaBhatia** [comment]
Added the changes @talboren. Please review.

**Review by talboren — APPROVED** [review]
LGTM! @KanvaBhatia mind adding a screenshot of how it looks before I merge it in?

**Pull request merged**
