### PR TITLE
docs: Keep issue #77

### LINKED ISSUE #77: Update readme to define what an alert is
**Is your feature request related to a problem? Please describe.**
Feature request

**Describe the solution you'd like**
Define what an alert is

**Additional context**
Got this from #devops on SRE

### PR DESCRIPTION
**Pull request by Rondiz**
Closes #77 

## 📑 Description

Added alert definition as requested in issue #77 

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [] All the tests have passed

### CODE REVIEW

**Comment by talboren** [comment]
@Rondiz hey and welcome to Keep!
Thank you so much for your first contribution.

TBH, I am not sure @shahargl meant explaining the "metadata" of what's an alert (in issue #77) but rather explain our alert YAML specification better so people can easily understand how we refer to an alert.

I'll let @shahargl answer more detailed in here.

**Comment by shahargl** [comment]
IMHO its find and we can merge it

**Review by shahargl — APPROVED** [review]
lgtm

**Comment by shahargl** [comment]
@Rondiz thanks for the contribution!

**Pull request merged**
