### PR TITLE
feat: Implemented ServiceNow provider to fetch and ingest incidents into Keep

### LINKED ISSUE #1261: [🔌 Provider]: ServiceNow ITSM
**Describe the provider you want to add**
Provider for https://www.servicenow.com/products/itsm.html

**Describe your use case**
I would love this provider to query all incidents, including metadata (participants, timeline, some other info?), as an event into Keep.

**Are you already using Keep?**
Yes/No

**Additional context**
This provider needs to fetch all incidents from the 3rd party retrospectively. I know that SNOW API is pretty complicated, and the configuration is not easy, so much attention will be paid to the documentation.

### PR DESCRIPTION
**Pull request by Anshgrover23**
/claim #1261
## Description

This PR introduces a new provider for integrating ServiceNow's ITSM incidents into Keep. It fetches incidents using the ServiceNow Table API and ingests them into Keep as events. 

### Fixes

Fixes #1261

### Changes Made

- Implemented ServiceNowProvider class to handle authentication and data retrieval.
- Added functions to fetch incidents from ServiceNow and transform them into Keep events.
- Updated README.md with setup instructions and usage examples.

### Testing

- Added unit tests for ServiceNowProvider to ensure proper data retrieval and transformation.
- Ran tests locally to verify functionality.

### Additional Notes

- ServiceNow API integration is complex; detailed documentation is provided to assist future maintenance.

### CODE REVIEW

**Review by unworld11 — CHANGES_REQUESTED** [review]
ingest_into_keep is incomplete,
if you chatgpt it, atleast crosscheck the code :)

**Comment by Anshgrover23** [comment]
@unworld11 what's your problem mam? Even you have chatgpt the problem I think you are more of jealous than solving the issue because I have taken your attempt of bounty you are getting jealous. I am waiting for the maintainer to reply not you.

**Comment by unworld11** [comment]
your code is incomplete ansh.
i am literally helping you,
you can crosscheck your code and the function i am talking about,
i don't mind the claim.
just making sure yk how open source works, it's barely about the bounty.
#buildinpublic :)

**Comment by Anshgrover23** [comment]
@unworld11 sorry bro, if you want you can take bounty. I am new to open source I don't know about these and I will take your advice politely and thanks for helping me brother. And sorry for my comment

**Comment by shahargl** [comment]
@Anshgrover23 hey bro, why did you remove all the comments from the code? it is very hard to understand what are the real code changes and what are not. Can you revert these changes so I'll be able to review only relevant code?

**Review by shahargl — CHANGES_REQUESTED** [review]
see comments

**Comment by Anshgrover23** [comment]
@shahargl i am doing undone the comments

**Comment by Anshgrover23** [comment]
@shahargl check done reapplied all the comments removed by mistake

**Review by shahargl — CHANGES_REQUESTED** [review]
I'm closing this PR now since it is not ready

**Comment by shahargl** [comment]
Closing until @Anshgrover23 will have end to end working.

**Pull request closed without merging**
