### PR TITLE
fix: Raise exception if condition name is missing

### LINKED ISSUE #105: Condition name should be aligned
This should be aligned and fixed ASAP.

image

cc: @shahargl

### PR DESCRIPTION
**Pull request by abhaykv04**
Closes #105

## 📑 Description
If a condition name is missing, the new implementation will throw an exception at the time of condition initialisation: "Condition must have a name".

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

Without condition name:
Screenshot 2023-04-28 at 7 30 35 PM

With condition name:
Screenshot 2023-04-28 at 7 30 50 PM

@talboren As discussed, I was trying to optimise the code to use only one pass over the conditions list, however, the list of initialised conditions is being used on line 113 to create a string of all conditions. We can discuss on how to optimise this without breaking the existing implementation.

Screenshot 2023-04-28 at 7 41 16 PM

cc: @shahargl

### CODE REVIEW

**Comment by talboren** [comment]
@abhaykv04 awesome work! This looks great and absolutely hit the point I was referring to.
I think we should also update all the examples/alerts/ files to adhere this change and update the documentation as well to mention that name is mandatory, wdyt?

**Comment by talboren** [comment]
> @abhaykv04 awesome work! This looks great and absolutely hit the point I was referring to. I think we should also update all the examples/alerts/ files to adhere this change and update the documentation as well to mention that name is mandatory, wdyt?

Once we get everything updated, we can continue to merge this.

**Comment by abhaykv04** [comment]
@talboren Yes, agree with you on the additional changes. I will get my new laptop tomorrow; I will do the required changes right after I get it.

**Comment by abhaykv04** [comment]
@talboren I did the required changes. Please have a look.

**Review by talboren — APPROVED** [review]
LGTM!

@abhaykv04 great work! @shahargl is now covering this with a test -- probably a good thing to contact him about and learn from.

Thank you so much for that!

**Pull request merged**
