### PR TITLE
feat(api): read only

### PR DESCRIPTION
**Pull request by shahargl**
close https://github.com/keephq/keep/issues/2498

### CODE REVIEW

**Comment by talboren** [comment]
1 thing we'll need to consider: how can we let someone "bypass" read only, i.e., the `simulate_alert` script or something

**Comment by shahargl** [comment]
@talboren added `KEEP_READ_ONLY_BYPASS_KEY` that, together with `KEEP_DEFAULT_API_KEYS` can do it.

Start Keep with
```
KEEP_READ_ONLY_BYPASS_KEY=1234
KEEP_DEFAULT_API_KEYS=admin_api_key:admin:1234
```

**Review by talboren — DISMISSED** [review]
LGTM

**Review by talboren — APPROVED** [review]
LGTM

**Pull request merged**
