### PR TITLE
fix(hashicorp): Incorrect work with json in vault code

### LINKED ISSUE #2927: [🐛 Bug]: Hashicorp doesn't work well with non-json secrets
Originally reported by @00041275 and fixed in https://github.com/keephq/keep/pull/2917

### PR DESCRIPTION
**Pull request by 00041275**
Incorrect work with json. The json logic for secret_value should be similar to that of secret manager

This problem not have issue .

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] I have updated the documentation as required

After making the change, my keephq, which stores secrets in vault, began to work well

close #2927

### CODE REVIEW

**Comment by talboren** [comment]
@00041275 thank you for this PR! can you explain what's not working? maybe you can create an issue for that?

**Comment by talboren** [comment]
@00041275 ping :)

**Comment by 00041275** [comment]
> of the Team first ne

sorry for waiting.
The fact is that when creating the provider, the script vault received json, but in the case of creating the API it was just a string. This broke the entire keephq initialization. I couldn't understand the reason. As a result, having studied similar implementations on Google, Amazon realized that it is impossible to convert data into json unambiguously when recording. That's the whole point why i rewrite row with json.loads.

**Comment by talboren** [comment]
@00041275 if I understand correctly, you are referring to API key? Have you had a chance to test your fix? is it working properly now? would love to chat more in [our Slack](https://slack.keephq.dev) if you're not in it already

**Comment by 00041275** [comment]
> @00041275 if I understand correctly, you are referring to API key? Have you had a chance to test your fix? is it working properly now? would love to chat more in [our Slack](https://slack.keephq.dev) if you're not in it already

Yes, that's right, this is an API key. Of course, everything works for me with the change. I'm not on Slack.

**Review by talboren — APPROVED** [review]
LGTM!

**Comment by talboren** [comment]
> > @00041275 if I understand correctly, you are referring to API key? Have you had a chance to test your fix? is it working properly now? would love to chat more in [our Slack](https://slack.keephq.dev) if you're not in it already
> 
> Yes, that's right, this is an API key. Of course, everything works for me with the change. I'm not on Slack.

Would love for you to join @00041275 :) LGTM'd and merging as soon as workflows pass!

**Comment by 00041275** [comment]
> ЛГТМ!

Thanks)

**Pull request merged**
