### PR TITLE
fix: #323 Implement Mattermost Provider

### PR DESCRIPTION
**Pull request by Vishal-Sikka**
- Added a new provider, MattermostProvider, to enable sending notifications to Mattermost channels.
- Implemented the notify method in the MattermostProvider class, which allows users to send alert messages to a Mattermost channel using a webhook URL.
- Created a new configuration class, MattermostProviderAuthConfig, to store Mattermost authentication details.
- Added validation checks to ensure that the Mattermost webhook URL is provided in the configuration

/claim #323

### CODE REVIEW

**Review by shahargl — CHANGES_REQUESTED** [review]
lgtm just add docs (under docs/)

**Comment by shahargl** [comment]
and add the svg

**Comment by Vishal-Sikka** [comment]
Added a mater most icon svg, Mattermost full logo svg, and docs check it out

**Review by shahargl — APPROVED** [review]
lgtm

**Pull request merged**
