### PR TITLE
refactor: refactor desc method

### PR DESCRIPTION
**Pull request by pehlicd**
## 📑 Description
This PR aims to unify desc method usage.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Review by talboren — CHANGES_REQUESTED** [review]
@pehlicd can you explain the motivation?

**Comment by pehlicd** [comment]
> @pehlicd can you explain the motivation?

Yeah sure, in some places `.desc()` method was used and also in other places `desc()` function was used so I've refactored them all to unify usage and also while using `.desc()` my ide was complaining that `Unresolved attribute reference 'desc' for class 'int'`. These were my motivation.

**Comment by talboren** [comment]
Thanks for clarification :) @pehlicd can you please verify that all functions return valid response with this change? just as a precaution

**Review by talboren — DISMISSED** [review]
LGTM!

**Review by talboren — APPROVED** [review]
LGTM

@shahargl any objections?

**Pull request closed without merging**
