### PR TITLE
feat: added aks provider

### LINKED ISSUE #407: AKS provider
Like the GKE provider - add the ability to query on kubernetes clusters running on Azure

### PR DESCRIPTION
**Pull request by devblin**
/claim #407

Closes #407 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by devblin** [comment]
@shahargl

**Comment by devblin** [comment]
@shahargl I have updated the docs!

**Comment by shahargl** [comment]
hey @devblin, nice work!

1. Can you add the aks icon?
2. Can you add the example workflow? (just rename it from basic slack to basic aks or something)

**Comment by devblin** [comment]
ok

**Pull request merged**
