### PR TITLE
feat: Refactoring workflow builder to use React Flow 

### LINKED ISSUE #1451: [🔨 Enhancement]: Refactoring workflow builder to use React Flow
https://reactflow.dev/

Overall, the workflow builder works as expected today, but the code is spaghetti, it's hard to add new features and validations are quite bad.
We want to keep the same state with Workflow Builder but adopting React Flow to enhance overall experience, cleaner code and making future features easier.

Since this task **does not have Figma**, imagination and use of current Keep theme is required :)

1. Enhance users Workflow Builder experience by look and feel
2. Add more validations
3. Clean code and make it easy to enhance/change things in the future

TBD

### PR DESCRIPTION
**Pull request by Bhavyajain21**
Closes #1451

### CODE REVIEW

**Comment by shahargl** [comment]
@Bhavyajain21 ready for review?

**Comment by Bhavyajain21** [comment]
Yes @shahargl

**Comment by talboren** [comment]
@Bhavyajain21 all issues that were raised in yesterday's demo are already implemented?

**Comment by Bhavyajain21** [comment]
Yes @talboren , we've tried to bring it as close as possible. Please review!

**Comment by rajeshj11** [comment]
> @Bhavyajain21 all issues that were raised in yesterday's demo are already implemented?

@talboren there are some things left. like validations and few things. we might need some time. will update you by EOD

FYI: @Bhavyajain21

**Comment by rajeshj11** [comment]
@talboren can you please check now?

**Comment by Bhavyajain21** [comment]
@talboren / @shahargl , the PR is now ready for review!

**Comment by talboren** [comment]
There's still a lot of code to be removed (everything related with `sequential-workflow-designer`)

cc: @Bhavyajain21 @rajeshj11

**Comment by talboren** [comment]
1. toolbox hides error message
CleanShot 2024-08-25 at 18 12 45
2. is this mandatory?
CleanShot 2024-08-25 at 18 13 32

**Comment by talboren** [comment]
https://github.com/user-attachments/assets/39131671-b601-41d7-8d4f-f11c2950468d

**Comment by rajeshj11** [comment]
> 1. toolbox hides error message
>    CleanShot 2024-08-25 at 18 12 45
> 2. is this mandatory?
>    CleanShot 2024-08-25 at 18 13 32

poin1 is fixed.
point 2 yes it is mandatory

**Comment by rajeshj11** [comment]
> CleanShot.2024-08-25.at.18.18.18.mp4

During the deployment of the preview workflow, an issue was encountered. This has now been resolved. However, if the problem persists, it may be due to the frontend service not being operational. Please verify that the frontend service is running when you are deploying the workflow.

**Comment by Bhavyajain21** [comment]
@talboren , the changes are pushed by @rajeshj11 . Can you please review?

**Comment by rajeshj11** [comment]
@talboren 
In the toolbox, you'll have 3 new "Triggers" dragable steps
It can only go in the beginning
and it defines what triggers the workflow has

1. We will add a new group to the toolbox. Please suggest a name for this group and the corresponding node names so I can begin working on it.
2. Once a node from this group is added, it will be disabled in the toolbox to prevent users from adding duplicate trigger nodes.
3. The start node cannot be removed, as it serves as the essential entry point for beginning the development process.
4. The initial connection from the start node must always link to one of the three specified nodes; other nodes will not be permitted for this connection. (I need clarification on this point.)

**Comment by rajeshj11** [comment]
> @Bhavyajain21 @rajeshj11 please note that tests are failing :(

on it

**Comment by rajeshj11** [comment]
> @Bhavyajain21 @rajeshj11 please note that tests are failing :(

now tests are passed. please check

**Comment by talboren** [comment]
A few comments:
Save button is redundant, it made me not understand what's wrong with the workflow until I clicked on it.
Triggers:
We need validation for workflow saying "No triggers were configured, please configure at least 1 trigger"
If I add manual trigger, there is not reason to check the box
We need to add some divider for the configuration part
If trigger was added, if should be removed from the toolbox (e,.g., it's confusing that I still have manual when it's already in the workflow and I can't do anything with it)
Instead of "Trigger end" change to "Workflow start"

image
image
image

**Review by talboren — APPROVED** [review]
LGTM

**Pull request merged**
