### PR TITLE
feat(ui): display workflow last update time in workflows page

### LINKED ISSUE #982: Display workflow last update time in workflows page
Display `last_updated` in workflows page

### PR DESCRIPTION
**Pull request by pehlicd**
Closes #982 

## 📑 Description
Display workflow last update time in workflows page.

## ✅ Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by shahargl** [comment]
@pehlicd you king! Does it get it from the backend or we need to send it from there?

**Comment by shahargl** [comment]
@pehlicd so do you want me to merge it or to keep close until you fix the backend?

**Comment by pehlicd** [comment]
@shahargl pushing backend fix in a sec.

**Comment by pehlicd** [comment]
now it is ready to merge @shahargl 🙂

**Comment by shahargl** [comment]
@pehlicd I'll try it and merge

**Pull request merged**
