### PR TITLE
fix: save and deploy change

### LINKED ISSUE #1937: [🔨 Enhancement]: Clicking "Save" on step doesn't save the changes on the server (only on deploy)
1. Clicking "Save" should actually save the workflow (maybe change and save & deploy)

### PR DESCRIPTION
**Pull request by rajeshj11**
Closes #1937
/claim #1937 

## 📑 Description
 we need to save and deploy

## ✅ Checks

- [X] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by rajeshj11** [comment]
@shahargl please review

**Comment by talboren** [comment]
@shahargl @rajeshj11 is this ready to be merged?

**Comment by rajeshj11** [comment]
@rajeshj11 waiting for review/feedback

**Comment by rajeshj11** [comment]
> @talboren waiting for review/feedback

@talboren ^^

**Review by shahargl — APPROVED** [review]
lgtm

**Pull request merged**
