### PR TITLE
feat: add topology applications

### LINKED ISSUE #1968: [➕ Feature] Allow to group services into applications in topology
**Reasoning**
If you happen to have huge system with a lot of services (100+ services), it would be beneficial to group them into applications and to enrich alerts with information about affected application. 

**Describe the solution you'd like**
As a user, I can select services on topology map and create an application with name, description and selected services. I could later alter all these or delete the application. As a user, I can see the affected application in alert or incident page.

### PR DESCRIPTION
**Pull request by Kiryous**
Closes #1968

- [x] Frontend: Create/manage application form
- [x] Frontend: Create application node and add child services to draw on react-flow 
- [x] Backend: CRUD
- [x] Backend: Tests
- [x] Frontend: update hooks to work with actual endpoints 
- [x] Frontend: ensure `useTopology()` hook doesn't cause multiple polling 
- [x] Docs

### CODE REVIEW

**Comment by talboren** [comment]
@Kiryous please note that build fails
`Module not found: Can't resolve '../topology/map/ui/topology-page' `

**Comment by Kiryous** [comment]
@talboren fixed

**Comment by talboren** [comment]
> @talboren fixed

now e2e tests failed (db couldn't start for some reason ;()

**Comment by talboren** [comment]
> > @talboren fixed
> 
> now e2e tests failed (db couldn't start for some reason ;()

@Kiryous 
`keep-backend-1  |     raise util.CommandError(multiple_heads) from mh
keep-backend-1  | alembic.util.exc.CommandError: Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '<branchname>@head' to narrow to a specific head, or 'heads' for all heads`

Seems like there were some migrations since you created this branch and your migration is out of date.

**Comment by Matvey-Kuk** [comment]
If I try to create an Application while not having any topology, clicking "Create Application" button don't do anything:
Screenshot 2024-09-29 at 15 55 34

**Comment by Matvey-Kuk** [comment]
Updating existing App, adding new service to it, getting error:
Screenshot 2024-09-29 at 16 10 11
Screenshot 2024-09-29 at 16 10 18

**Comment by Matvey-Kuk** [comment]
"Show on the map" feature doesn't work for me if nodes are far from each other vertically. It positions the view in between and the view is too zoomed-in to show all services for the app.

**Comment by Matvey-Kuk** [comment]
Maybe enable filter if I click "Show on the map"? Filter works well.
Screenshot 2024-09-29 at 21 12 14

**Review by talboren — APPROVED** [review]
LGTM

**Pull request merged**
