### PR TITLE
feat: Linear provider

### LINKED ISSUE #310: Provider: Linear
**Describe the provider you want to add**
Linear is a new task management tool for Agile teams, loosely built around Scrum, KanBan and Cycles.

**Describe your use case**
Linear works best for developers, but our Dev/Ops Platform team also uses it. I could see an integration to Keep where we create tickets in a Linear project after a set number of alerts have been detected (or manually at the push of a button).

**Are you already using Keep?**
Evaluating

### PR DESCRIPTION
**Pull request by Hitesh-sisara**
fix #310 

/claim #310

### CODE REVIEW

**Comment by talboren** [comment]
Thanks! Will review it ASAP :)

Can you take a look at https://docs.keephq.dev/ and add the provider documentation? (How to get the webhook url, etc.)

Please also add a PNG of Linear icon to keep-up/public/icons 🙏🏼

**Review by shahargl — CHANGES_REQUESTED** [review]
lgtm but please add docs (under docs/) how to use / get API token

**Comment by Hitesh-sisara** [comment]
Documentation done

**Review by shahargl — APPROVED** [review]
lgtm

**Pull request merged**
