### PR TITLE
fix(ui): Small and medium screen responsiveness

### LINKED ISSUE #412: Make the tiles looks good on small screen
Fix the 13" providers page issue

### PR DESCRIPTION
**Pull request by D-Lite**
UI update
Thanks for creating this pull request 🤗

Closes  #412 

## 📑 Description
#412 : Providers page overflow on both medium and smaller screens 

- [x] Mobile responsiveness
- [x] Medium screen responsiveness
- [x] Mobile sidepanel fix
- [x] Medium sidepanel fix 
-->

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information
Small screen before
keepuioverflow

Small screen after
keepuioverflowreset

Medium screen after
keepuitab
9e52f96-ddce-4ff7-a508-58fb05387758)

### CODE REVIEW

**Comment by talboren** [comment]
@D-Lite thank you so much man! I wanna switch from grid to flex to make it really responsive and also make sure the sidebar content is properly set.

**Comment by talboren** [comment]
@D-Lite do you want to take it and try to make it flex? I can do it tomorrow/Sunday

**Comment by D-Lite** [comment]
I've some personal bias for flex too 😂. I wanted to switch it up earlier but decided to just go with what was currently been used.

**Comment by D-Lite** [comment]
I'll work on a flex update and send in a PR soon

Thank you  @talboren

**Comment by talboren** [comment]
@D-Lite you are the best, I’m here for anything. Lmk if I can help

**Comment by D-Lite** [comment]
Yes, I'll reach out if there's a need

**Comment by D-Lite** [comment]
@talboren , here you go

**Pull request merged**
