### PR TITLE
fix: validate incident_id is UUID

### LINKED ISSUE #2057: [🐛 Bug]: if incident id is not UUID the backend returns 500
CleanShot 2024-10-01 at 14 03 03@2x

### PR DESCRIPTION
**Pull request by amritansh22**
Closes #2057 

## 📑 Description
incident_id is of type UUID. When it is passed a string it causes an Internal Server Error. 
To avoid this have added a validation of the input param. Now the error returned will be 422. 

Screenshot 2024-10-03 at 9 30 31 AM

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by amritansh22** [comment]
Hey @shahargl 
Can you please review this PR ?

**Review by talboren — APPROVED** [review]
LGTM

**Comment by amritansh22** [comment]
Thanks for the review @VladimirFilonov 
Have addressed the review comments now 🙌

**Review by VladimirFilonov — APPROVED** [review]
Looks good now, thank you!

**Pull request merged**
