### PR TITLE
feat: keycloak (WIP)

### PR DESCRIPTION
**Pull request by shahargl**

### CODE REVIEW

**Comment by talboren** [comment]
Closing until we further get to this

**Comment by lukasmrtvy** [comment]
@talboren Hi, why is this closed? Thanks

**Comment by talboren** [comment]
> @talboren Hi, why is this closed? Thanks

Closed until we get more time to work on this integration

**Comment by shahargl** [comment]
@lukasmrtvy any context on why you interested in Keycloak?

**Comment by lukasmrtvy** [comment]
@Shah-Panam I suggested a much easier implementation here https://github.com/keephq/keep/issues/1203, but seems there is no progress so far. 

@shahargl friendly ping

**Comment by shahargl** [comment]
hey @Shah-Panam, @lukasmrtvy ,

as per @lukasmrtvy said, we discussed the option to support oauth2-proxy. It makes sense; maybe I'll prioritize it to push it this week or so.  However, as I see it, it is pretty different from Keycloak since Keycloak gives much more power to Keep. For example, a user will be able to configure its IdP (e.g. okta) directly from Keep, or to later support group roles etc.

(anyway, any contributions are welcome here and I'll be more than happy to help with the implementation)

**Comment by Shah-Panam** [comment]
Hey @lukasmrtvy @shahargl ,

Any of the solution works for us. We can easily integrate keycloak with Oauth2-Proxy (we already have some services deployed that way). But as @shahargl said, giving option to configure openid connectors like Keycloak directly will give far more control over the authentication and authorization. Also, being able to integrate multiple Identity Providers will be an added benefit.

I am mainly a DevOps engineer, but I will go through the code and see where I can help out!

**Comment by Shah-Panam** [comment]
Hey @shahargl ,

Friendly ping. Is there any timeline on this?

**Comment by talboren** [comment]
Hey @Shah-Panam, @lukasmrtvy,

We're working on making this happen ASAP, but there are a few other items with higher priority right now.
In the meanwhile, I'd love invite you for a quick chat to see if I can help you with other solutions in the meanwhile (we do support SSO on the cloud version and perhaps it can help you in the meantime).
[Join our Slack?](https://slack.keephq.dev)

Looking forward to chatting!

**Pull request closed without merging**
