### PR TITLE
chore: remove deprecated utcnow

### PR DESCRIPTION
**Pull request by thomas-chauvet**
## 📑 Description

Remove deprecated `datetime.utcnow` replaced by `datetime.now(tz=timezone.utc)`.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Review by talboren — DISMISSED** [review]
LGTM! thank you

**Comment by talboren** [comment]
@thomas-chauvet seems like there are a few failing validations, can you take a look? 🙏🏼

**Comment by thomas-chauvet** [comment]
Yes, sorry I've missed an import :)

**Review by talboren — APPROVED** [review]
LGTM!

**Comment by talboren** [comment]
> Yes, sorry I've missed an import :)

Still 2 fails 😅 
CleanShot 2024-06-27 at 14 56 59@2x

**Comment by talboren** [comment]
> > Yes, sorry I've missed an import :)
> 
> Still 2 fails 😅 CleanShot 2024-06-27 at 14 56 59@2x

@thomas-chauvet once you can solve these 2 small things and the conflict from latest merge, let me know and I'll merge it :)

**Comment by shahargl** [comment]
closing since no comment and conflicts are starting to pile up, feel free to re-open when ready.

**Pull request closed without merging**
