### PR TITLE
feat: Ability to set labels or custom fields like Component/s when creating Jira ticket

### LINKED ISSUE #699: Ability to set labels or custom fields like Component/s when creating Jira ticket
**Describe the solution you'd like**
When I create a Jira ticket I would like to be able to set labels or custom fields so that I am able to use those fields for filtering in Jira.

I would like to set the label, component and fill in a custom field.

See:
https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-post
https://support.atlassian.com/jira-cloud-administration/docs/configure-issue-custom-fields/

### PR DESCRIPTION
**Pull request by Min2who**
closes #699 
## 📑 Description

Ability to set labels or custom fields like Component/s when creating Jira ticket

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Review by talboren — CHANGES_REQUESTED** [review]
@Min2who great job! I didn't get a chance to test it yet but seems like a solid solution.
while components and labels seems OK, I didn't really get the `customfield_10027` part. I think we should be able to support X custom fields (as every company is different and has it's own custom fields).
Perhaps have that function get a `custom_fields: dict[str, str]` where the key is the custom_field id and the value is the actual value to put inside? (just a though).

Let me know your thoughts.

**Comment by Min2who** [comment]
> @Min2who great job! I didn't get a chance to test it yet but seems like a solid solution. while components and labels seems OK, I didn't really get the `customfield_10027` part. I think we should be able to support X custom fields (as every company is different and has it's own custom fields). Perhaps have that function get a `custom_fields: dict[str, str]` where the key is the custom_field id and the value is the actual value to put inside? (just a though).
> 
actually i was too confused about that part
> Let me know your thoughts.
looks fine to me working on it

**Comment by talboren** [comment]
> > @Min2who great job! I didn't get a chance to test it yet but seems like a solid solution. while components and labels seems OK, I didn't really get the `customfield_10027` part. I think we should be able to support X custom fields (as every company is different and has it's own custom fields). Perhaps have that function get a `custom_fields: dict[str, str]` where the key is the custom_field id and the value is the actual value to put inside? (just a though).
> 
> actually i was too hesitant about that part
> 
> > Let me know your thoughts.
> 
> looks fine to me working on it

Looking forward

**Review by talboren — APPROVED** [review]
lgtm!

**Comment by talboren** [comment]
@Min2who seems like tests are failing. Do you mind taking a look and fixing? we can push that in once they pass.

**Comment by Min2who** [comment]
> @Min2who seems like tests are failing. Do you mind taking a look and fixing? we can push that in once they pass.

done @talboren

**Pull request merged**
