### PR TITLE
chore: remake repo main README.md

### LINKED ISSUE #1809: [📃 Docs]: remake repo main README
README is outdated (for example, screenshots/GIFs are irrelevant)

### PR DESCRIPTION
**Pull request by 4F24L**
Closes #1809  

### Key Changes:
- Improved alignment and structure for better readability.
- New Recorded GIFs added
- Enhanced section headers for clarity and accessibility.
- Incorporated tables for GIFs to organize content visually.
- Reformatted provider logos for consistency.

Would you like to make any additional tweaks or adjustments to this redesign?

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

- New screen recorded GIFs added.
- Top contributors list updated.

### CODE REVIEW

**Comment by talboren** [comment]
Thank you @4F24L! I’ll review it ASAP and suggest further edits

**Comment by 4F24L** [comment]
Excited to see my first PR getting merged.

**Comment by talboren** [comment]
@4F24L Thank you so much for this! I have a few points I would like you to address. Besides the "styling" of the page itself, the information is also out dated and doesn't send out the Keep "message" perfectly. I would suggest opening https://www.keephq.dev and trying to align the message there to what we currently have in README. The images are great but some text needs to be adjusted. Would you like to give it another try?

**Comment by 4F24L** [comment]
Okay, I will try to make changes as per your suggestion.

**Comment by shahargl** [comment]
@4F24L I'm not sure about this issue, since the README is kinda "Keep's face" and I feel should be made by the core maintainers with the most context of what Keep does.

**Comment by shahargl** [comment]
For example, we want to add actual examples and videos/screenshots from the platform.

**Comment by 4F24L** [comment]
> For example, we want to add actual examples and videos/screenshots from the platform.

I added the actual images and screenshots from the platform. please check that out.

**Comment by 4F24L** [comment]
> @4F24L Thank you so much for this! I have a few points I would like you to address. Besides the "styling" of the page itself, the information is also out dated and doesn't send out the Keep "message" perfectly. I would suggest opening https://www.keephq.dev and trying to align the message there to what we currently have in README. The images are great but some text needs to be adjusted. Would you like to give it another try?

Checked that website, and I'm confused about that. Should I make changes to the landing page also?? or the data from the website should be updated on the readme file.

**Comment by 4F24L** [comment]
I made some little changes. 

- Added landing page screenshot at the top.

review this !

**Comment by talboren** [comment]
@4F24L I'm sorry for the confusion on this one. I have just synced with @shahargl and will go ahead to close the issue and PR.
Thank you so much for the effort you put on this! I'll be more than happy to collaborate together on another issue if you will!

**Pull request closed without merging**
