### PR TITLE
refactor: split incidents detail page

### LINKED ISSUE #2356: [ 🏎️ Performance ]: Split Incident detail page tabs into pages
## Problem
Right now the /incidents/[id]/ fetches and renders all the data at once: alerts, timeline, activity, topology, however user might need only alerts for example.

Also there's no way to share the link to exact tab of the incident page because URL doesn't have tab state.

At last the incident detail page performs poorly if ~900 alerts added to incidents and profiling is hard due to all tabs rendered at once.

## Solution
Create separate pages for each tab, e.g:
```
/incidents/[id]/
-------------- topology.tsx
-------------- alerts.tsx
etc
```
and update Tabs to use only styling

### PR DESCRIPTION
**Pull request by Kiryous**
Closes #2356 

## TODO:

- [x] Ensure the instant client navigation with loading state
- [ ] Check if fetch requests (for meta and for ssr) being deduplicated
- [x] SSR cold-load of the segment
  - [x]  /alerts
  - [x] /topology
  - [x] /activity
  - [x] /timeline
  - [x] /workflows
  - [x] /chat
 - [x] client navigation to the segment
   - [x]  /alerts
   - [x] /topology
   - [x] /activity
   - [x] /timeline
   - [x] /workflows
   - [x] /chat

## ✅ Checks
- [ ] Associate alerts to incident
- [ ] Go to incident detail page
   - [ ] Run workflow
   - [ ] Edit incident name

### CODE REVIEW

**Review by shahargl — APPROVED** [review]
lgtm

**Review by shahargl — DISMISSED** [review]
Lgtm

**Review by Matvey-Kuk — CHANGES_REQUESTED** [review]
Looks like linked incidents are missing on the first screen :(

**Review by shahargl — APPROVED** [review]
lgtm

**Review by Matvey-Kuk — APPROVED** [review]

**Pull request merged**
