### PR TITLE
feat: added basic new workflows ui

### LINKED ISSUE #1363: [🔨 Enhancement]: Introducing new design to Workflows page
@fivenp contributed this design for Workflows page:

1. Empty state, no alerts
no alerts

2. Empty state, with alerts
with alerts

We have many workflow examples in https://github.com/keephq/keep/tree/main/examples/workflows which we can use as "mocked workflows"

* The navbar already changed, no need to implement the one in the designs here.
* Need to implement the mechanism that gets the mocked workflows from https://github.com/keephq/keep/tree/main/examples/workflows and displays them when alerts exist
* If for some reason, the frontend is unable to fetch the workflow examples, some indicative warning message should be displayed instead of the mocked workflows. (e.g., could not fetch workflows)

TBD

Figma files are available for the grabber ;)

### PR DESCRIPTION
**Pull request by rajeshj11**
/claim #1363

Closes #1363 

## 📑 Description

new workflow Ui

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by rajeshj11** [comment]
I was unable to find anything related to the API documentation. Therefore, I am providing all the relevant details here

For new Workflow UI.  
1. Redesign the workflow Card
     The workflow card needs execution records (currently limited to 15) for the graph. To achieve this, the following changes 
      were made in the backend:
        1. **Query Search Parameter:** A new query search parameter called **is_v2** has been added, which accepts a boolean 
            (default is false).
        2. **Grouped Workflow Executions:** When a request is made with **/workflows?is_v2=true**, workflow executions are grouped 
           by workflow.id.
        3. **Response Updates:** The response includes the following new keys and their respective information:
              -> last_executions:  Used for the workflow execution graph.
              ->last_execution_started: Used for showing the start time of execution in real-time.
               
**Sample requests and their responses:**

when the Request is made with is_v2 enable:
`curl --location 'http://localhost:8080/workflows?is_v2=true' \
--header 'Authorization: Bearer keep-token-for-no-auth-purposes' \
--header 'Content-Type: application/json'`

response to the above request:
`[
{
        "id": "5ee5aa35-00cb-4aa3-8ae8-22a1814603e6",
        "name": "planner-demo",
        "description": "Create a task in planner.",
        "created_by": "admin@keephq",
        "creation_time": "2024-07-18T14:05:53.061972",
        "triggers": [
            {
                "type": "interval",
                "value": 15
            }
        ],
        "interval": 15,
        "last_execution_time": "2024-07-19T07:02:00.006502",
        "last_execution_status": "providers_not_configured",
        "providers": [
            {
                "type": "planner",
                "id": null,
                "name": "planner",
                "installed": false
            }
        ],
        "workflow_raw_id": "planner-demo",
        "workflow_raw": "id: planner-demo\ndescription: Create a task in planner.\ntriggers:\n- type: interval\n  value: 15\nname: planner-demo\nactions:\n- name: create-planner-task\n  provider:\n    config: ' {{ providers.planner }} '\n    on-failure:\n      retry:\n        count: 2\n        interval: 2\n    type: planner\n    with:\n      plan_id: tAtCor_XPEmqTzVqTigCycgABz0K\n      title: Keep HQ Task1\n",
        "revision": 1,
        "last_updated": "2024-07-18T14:05:53.062014",
        "invalid": false,
        "last_executions": [
            {
                "status": "providers_not_configured",
                "execution_time": 0.026236,
                "started": "2024-07-19T07:02:00.006502"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 0.034553,
                "started": "2024-07-19T07:01:44.725391"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 0.025167,
                "started": "2024-07-19T07:01:29.524701"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 0.031004,
                "started": "2024-07-19T07:01:14.400831"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 0.025889,
                "started": "2024-07-19T07:00:59.276224"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 0.061561,
                "started": "2024-07-19T07:00:44.079067"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 0.866926,
                "started": "2024-07-18T18:25:43.773209"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 3.195787,
                "started": "2024-07-18T18:25:28.179127"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 2.619036,
                "started": "2024-07-18T18:25:11.786847"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 0.798137,
                "started": "2024-07-18T18:24:55.797534"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 1.923669,
                "started": "2024-07-18T18:24:39.840848"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 1.661075,
                "started": "2024-07-18T18:24:24.329428"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 1.245263,
                "started": "2024-07-18T18:24:08.309625"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 0.416496,
                "started": "2024-07-18T18:23:52.305060"
            },
            {
                "status": "providers_not_configured",
                "execution_time": 0.201373,
                "started": "2024-07-18T18:23:36.313849"
            }
        ],
        "last_execution_started": "2024-07-19T07:02:00.006502"
    }
]`

When the request is made without is_v2:
`curl --location 'http://localhost:8080/workflows' \
--header 'Authorization: Bearer keep-token-for-no-auth-purposes' \
--header 'Content-Type: application/json'`

response for above request
`{
        "id": "5ee5aa35-00cb-4aa3-8ae8-22a1814603e6",
        "name": "planner-demo",
        "description": "Create a task in planner.",
        "created_by": "admin@keephq",
        "creation_time": "2024-07-18T14:05:53.061972",
        "triggers": [
            {
                "type": "interval",
                "value": 15
            }
        ],
        "interval": 15,
        "last_execution_time": "2024-07-19T07:05:33.400819",
        "last_execution_status": "providers_not_configured",
        "providers": [
            {
                "type": "planner",
                "id": null,
                "name": "planner",
                "installed": false
            }
        ],
        "workflow_raw_id": "planner-demo",
        "workflow_raw": "id: planner-demo\ndescription: Create a task in planner.\ntriggers:\n- type: interval\n  value: 15\nname: planner-demo\nactions:\n- name: create-planner-task\n  provider:\n    config: ' {{ providers.planner }} '\n    on-failure:\n      retry:\n        count: 2\n        interval: 2\n    type: planner\n    with:\n      plan_id: tAtCor_XPEmqTzVqTigCycgABz0K\n      title: Keep HQ Task1\n",
        "revision": 1,
        "last_updated": "2024-07-18T14:05:53.062014",
        "invalid": false,
        "last_executions": null,
        "last_execution_started": null
    }`


              
2. Add Mock Workflows (6 Random Workflows on Every Request)
   To add mock workflows, a new backend API endpoint has been created: /workflows/random-templates.
          1. **Fetching Random Templates:** When a request is made to this endpoint, all workflow YAML/YML files are read and 
             shuffled randomly.
          2. **Response:** Only the first 6 files are parsed and sent in the response.
          
          
 Sample request for getting random templates:
 `curl --location 'http://localhost:8080/workflows/random-templates' \
--header 'Authorization: Bearer keep-token-for-no-auth-purposes' \
--header 'Content-Type: application/json'`   

Response to above request
`[
{
        "workflow": {
            "id": "sentry-alerts",
            "description": "handle alerts",
            "triggers": [
                {
                    "type": "alert",
                    "filters": [
                        {
                            "key": "source",
                            "value": "sentry"
                        },
                        {
                            "key": "severity",
                            "value": "critical"
                        },
                        {
                            "key": "service",
                            "value": "r\"(payments|ftp)\""
                        }
                    ]
                }
            ],
            "actions": [
                {
                    "name": "send-slack-message-team-payments",
                    "if": "'{{ alert.service }}' == 'payments'",
                    "provider": {
                        "type": "slack",
                        "config": " {{ providers.team-payments-slack }} ",
                        "with": {
                            "message": "\"A new alert from Sentry: Alert: {{ alert.name }} - {{ alert.description }}\n{{ alert}}\"\n"
                        }
                    }
                },
                {
                    "name": "create-jira-ticket-oncall-board",
                    "if": "'{{ alert.service }}' == 'ftp' and not '{{ alert.ticket_id }}'",
                    "provider": {
                        "type": "jira",
                        "config": " {{ providers.jira }} ",
                        "with": {
                            "board_name": "Oncall Board",
                            "issuetype": "Task",
                            "summary": "{{ alert.name }} - {{ alert.description }} (created by Keep)",
                            "description": "\"This ticket was created by Keep.\nPlease check the alert details below:\n{code:json} {{ alert }} {code}\"\n",
                            "enrich_alert": [
                                {
                                    "key": "ticket_type",
                                    "value": "jira"
                                },
                                {
                                    "key": "ticket_id",
                                    "value": "results.issue.key"
                                },
                                {
                                    "key": "ticket_url",
                                    "value": "results.ticket_url"
                                }
                            ]
                        }
                    }
                }
            ]
        },
        "name": "sentry-alerts",
        "workflow_raw": "name: sentry-alerts\nworkflow:\n  actions:\n  - if: '''{{ alert.service }}'' == ''payments'''\n    name: send-slack-message-team-payments\n    provider:\n      config: ' {{ providers.team-payments-slack }} '\n      type: slack\n      with:\n        message: '\"A new alert from Sentry: Alert: {{ alert.name }} - {{ alert.description\n          }}\n\n          {{ alert}}\"\n\n          '\n  - if: '''{{ alert.service }}'' == ''ftp'' and not ''{{ alert.ticket_id }}'''\n    name: create-jira-ticket-oncall-board\n    provider:\n      config: ' {{ providers.jira }} '\n      type: jira\n      with:\n        board_name: Oncall Board\n        description: '\"This ticket was created by Keep.\n\n          Please check the alert details below:\n\n          {code:json} {{ alert }} {code}\"\n\n          '\n        enrich_alert:\n        - key: ticket_type\n          value: jira\n        - key: ticket_id\n          value: results.issue.key\n        - key: ticket_url\n          value: results.ticket_url\n        issuetype: Task\n        summary: '{{ alert.name }} - {{ alert.description }} (created by Keep)'\n  description: handle alerts\n  id: sentry-alerts\n  triggers:\n  - filters:\n    - key: source\n      value: sentry\n    - key: severity\n      value: critical\n    - key: service\n      value: r\"(payments|ftp)\"\n    type: alert\n",
        "workflow_raw_id": "sentry-alerts"
    }
]`      

**Note:** 
If the request is made without **is_v2**, the data returned will be the same as before, with the new keys (`last_executions` and `last_execution_started`) having null values in the response.

**Review by talboren — CHANGES_REQUESTED** [review]
CleanShot 2024-07-21 at 13 52 12
CleanShot 2024-07-21 at 13 53 15

1. It looks pretty bad on large screen :(
2. It's too much different from the Figma design
3. when workflow runs all the chart gets screwed
4. trigger is clickable but doesn't show you the trigger rules (like before change)
5. No data available 1?
6. when in progres should look like this:
CleanShot 2024-07-21 at 13 55 02
7. please add some of the documentation your shared in this pr to the code itself (for example, v2)

Let's make it look more close to the figma and push it in!

**Comment by rajeshj11** [comment]
> CleanShot 2024-07-21 at 13 52 12 CleanShot 2024-07-21 at 13 53 15
> 
> 1. It looks pretty bad on large screen :(
> 2. It's too much different from the Figma design
> 3. when workflow runs all the chart gets screwed
> 4. trigger is clickable but doesn't show you the trigger rules (like before change)
> 5. No data available 1?
> 6. when in progres should look like this:
>    CleanShot 2024-07-21 at 13 55 02
> 7. please add some of the documentation your shared in this pr to the code itself (for example, v2)
> 
> Let's make it look more close to the figma and push it in!

Thanks for the feedback. will work on it

**Review by talboren — CHANGES_REQUESTED** [review]
Basically LGTM but left a few comments (+bug) in our Slack conversation, will copy it here soon.

**Review by talboren — APPROVED** [review]
LGTM

**Pull request merged**
