### PR TITLE
fix: Optimize UI for smaller screens

### PR DESCRIPTION
**Pull request by srikary12**
Closes # 1220
/claim #1220 

## 📑 Description

UI optimised for smaller screens

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

Screenshot 2024-06-10 at 1 27 45 PM
 src="https://github.com/keephq/keep/assets/121927567/f12393dd-ff89-4965-ac47-1b139c66f7d2">

Screenshot 2024-06-10 at 1 28 07 PM

### CODE REVIEW

**Comment by Matvey-Kuk** [comment]
@srikary12, thank you for the contribution! I see two issues here:
1) Provider's page responsive class modifiers depend on the content which creates such a state when some objects are already updated, and others are not. Example screen width: 1260:
Screenshot 2024-06-10 at 14 06 29

2) Moving code to the bottom of the webhook page creates a mix of buttons, maybe there is a better solution, like conditional horizontal scroll for the code block?:
Screenshot 2024-06-10 at 14 05 23

**Comment by srikary12** [comment]
@Matvey-Kuk fixed the requests, let me know how it goes.

**Comment by Matvey-Kuk** [comment]
Smth wrong is happened with the provider "edit" panel Screenshot 2024-06-13 at 10 22 51

**Comment by Matvey-Kuk** [comment]
Also, the "Modify" button margins disappeared, button should not stick to the logo:

Old:
Screenshot 2024-06-13 at 10 25 04

New:
Screenshot 2024-06-13 at 10 25 10

**Comment by srikary12** [comment]
I'll fix those, not sure what happened with provider edit panel

**Comment by srikary12** [comment]
I've added padding to the buttons, providers edit page is working fine for me
Screenshot 2024-06-15 at 3 01 44 PM
Screenshot 2024-06-15 at 3 02 07 PM

**Comment by shahargl** [comment]
@Matvey-Kuk wdyt?

**Comment by Matvey-Kuk** [comment]
@srikary12 thank you! Merging.

**Review by Matvey-Kuk — APPROVED** [review]

**Comment by Matvey-Kuk** [comment]
This PR broke "Alert Groups" for large screens, reverting.

**Pull request merged**
