### PR TITLE
fix: Optimize UI for smaller screens (#1220)

### LINKED ISSUE #1220: Optimize UI for smaller screens
**Please don't assign to yourself if you are not going through the interview process:**

> We are hiring at Keep, and one of the stages in our hiring process is a test task. To make working on a test task more fun, we ask candidates to take any issue from our public GitHub. We also assign a small bounty to thank candidates for their time. Issues with the bounty are popular, so **this particular issue is "held" for candidates going through the interview** process. Btw, check our open positions if you want to work at Keep! https://www.ycombinator.com/companies/keep

Currently, Keep's UI is optimized for larger screens only. This issue is a series of minor frontend issues I'm facing as a MacBook (13-inch display) user. Take it if you would like to demonstrate UI skills. I'm pretty sure I didn't catch all of the issues ;)

1) Margins in the list of Providers (and even overflow for some items):
Screenshot 2024-06-09 at 15 47 22

2) Overflow:
Screenshot 2024-06-09 at 15 48 19

3) Margins on the bottom of the Provider configuration page:
Screenshot 2024-06-09 at 15 48 48

4) Give me more space!
Screenshot 2024-06-09 at 15 53 32

5) Too vertical ;) 
Screenshot 2024-06-09 at 15 54 28

### PR DESCRIPTION
**Pull request by Kiryous**
Closes #1220

## 📑 Description
Fix overflow, padding, and other issues that occur on smaller screens (<1280 px):
- `page-container` and `card-container` classes were introduced to unify the paddings 
- `min-w-0` added to places where the overflow of flex container happened
-  fallback to one column where appropriate 

Known issues:
- new container classes may not be updated everywhere yet
- there's room for further changes requiring design decisions; intentionally left them for the follow-up PRs 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

[ <br/>Watch Loom with comparison](https://www.loom.com/share/89f3b17fd44c4369a061782bfac9d84a)

### CODE REVIEW

**Review by talboren — DISMISSED** [review]
LGTM!

**Comment by talboren** [comment]
@Kiryous it seems like for some reason there is some E2E test failing due to the changes introduced in this branch. Can you please see if you can fix it?

**Comment by Kiryous** [comment]
@talboren hey! yeah, I noticed it, but it seems bug in tests rather than bug in code, since I could see the provider's card in headful mode. But maybe I'm wrong. I'm  out on vacation till August 23, and could look into it on return.

**Review by Matvey-Kuk — DISMISSED** [review]

**Comment by Matvey-Kuk** [comment]
@Kiryous we're kinda blocked from merging this while it's breaking tests anyway :(

**Comment by talboren** [comment]
@Kiryous @Matvey-Kuk I'm closing this PR for now as it is stale and we can re-open it once @Kiryous is able to fix the small issue here. 🙏🏼

**Review by talboren — APPROVED** [review]
lgtm

**Comment by Kiryous** [comment]
> lgtm

@talboren thanks for reviewing and approving. Do not merge yet, please, wanna make a few minor additions

**Comment by Kiryous** [comment]
@talboren added a fix so tiles of linked providers won't jump on hover. good to go!

**Comment by Kiryous** [comment]
@Matvey-Kuk it seems the merging is blocked because the Vercel deployment is need authorization. Could you please authorize it?

**Review by Matvey-Kuk — APPROVED** [review]

**Comment by Matvey-Kuk** [comment]
@Kiryous congrats and thank you for the contribution! <3

**Pull request merged**
