### PR TITLE
feat: Add close alert and comment on alert for Opsgenie provider

### LINKED ISSUE #618: opsgenie provider: add close alert and comment on alert

### PR DESCRIPTION
**Pull request by rmaceissoft**
Closes #618 

## 📑 Description

- [x] Add close alert as provider method for Opsgenie
- [x] Add comment alert as provider method for Opsgenie
- [x] Improve the provider method parameters type parsing. Define a class method for it `ProvidersFactory._get_method_param_type`

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation  
- [x] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

- Provider methods are only visible in the alerts context menu (`AlertMenu`)  after visiting the providers page before accessing the alerts page.
- The alert_id parameter is not automatically filled, but it should be auto-populated in read-only mode.
- The _alert state_ may change after specific actions are executed. For example, after closing an alert, it could be beneficial to exclude or highlight it once the close action is completed. A possible solution to this could be implementing a post-provider method hook.

### CODE REVIEW

**Comment by shahargl** [comment]
testing...
CleanShot 2024-01-24 at 12 02 20@2x

**Comment by shahargl** [comment]
Hey @rmaceissoft!

First -  it looks great and we are making nice progress.
Second - did you try testing it end to end? because the basic flows didn't work for me:
1. When running the API, it failed to start since `providers_factory` didn't support the input args you passed. I've pushed a fixed for that (see `providers_factory.py`)
2. I tried to use the create_alert and comment_alert from the UI and the inputs doesn't work - 
CleanShot 2024-01-24 at 12 16 00@2x

CleanShot 2024-01-24 at 12 11 15@2x

CleanShot 2024-01-24 at 12 11 15@2x

**Review by shahargl — CHANGES_REQUESTED** [review]
see comment

**Comment by shahargl** [comment]
@rmaceissoft cool for adding tests! are we ready for merge?

**Comment by shahargl** [comment]
@rmaceissoft are you still working on it?

**Comment by rmaceissoft** [comment]
> @rmaceissoft are you still working on it?

@shahargl I'm not, just waiting for your feedback

**Comment by shahargl** [comment]
merged @rmaceissoft - thank you!

**Pull request merged**
