### PR TITLE
[FEAT]: Runbooks queried by Github and Gitlab

### LINKED ISSUE #1780: [➕ Feature]: Runbooks queried by GitHub and GitLab providers
We want to introduce "Runbooks" as a content queried from GitHub and GitLab providers. For the beginning, Runbook in Keep will be a "title" and a link to the ".md" file.

# Update providers

Introduce "Runbooks" as data type providers could query from the source. Similar to "alerts", or "topology".
Screenshot 2024-09-01 at 18 32 29

For GitHub and Gitlab, I think the "Optional settings" (similar to prometheus) should allow choosing the repo and the path with ".md" files.
Screenshot 2024-09-01 at 18 32 16

# Runbooks page

Should represent all runbooks and Incidents those Runbooks are attached to. Just a table.

# Update the Incident page

Allow attaching/unattaching of runbooks to the incident.

### PR DESCRIPTION
**Pull request by Mubashirshariq**
Closes #1780 
/claim #1780

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by Matvey-Kuk** [comment]
Hey @Mubashirshariq how is it going? :)

**Comment by Mubashirshariq** [comment]
@Matvey-Kuk  I was busy with some other work,i have started working on it again today.

**Comment by talboren** [comment]
@Mubashirshariq I can see you pushed some changes recently. is this already ready for review?
Please note that there is a small conflict with `NoiseRecutionLinks.tsx`

**Comment by Mubashirshariq** [comment]
> @Mubashirshariq I can see you pushed some changes recently. is this already ready for review? Please note that there is a small conflict with `NoiseRecutionLinks.tsx`

it will take some time ,will ping you once it is ready to review

**Comment by Matvey-Kuk** [comment]
@Mubashirshariq could you please summarise the status of the PR? Are there outstanding question? :)

**Comment by Mubashirshariq** [comment]
@Matvey-Kuk  we are working on attaching and deleting an incident.shall i change this PR from draft to ready to review ,maybe you can give a shot how it is working rn

**Comment by talboren** [comment]
Closing this as it is a duplicate of https://github.com/keephq/keep/pull/2104

**Pull request closed without merging**
