### PR TITLE
feat: add time frame

### LINKED ISSUE #1770: [➕ Feature]: Timeframe definition for the dashboard
For now, user can't look at a dashboard's data "week ago" or for a specific dates. Add a timeframe selector to allow users select "timedate start" and "timedate end" for the current dashboard.
Screenshot 2024-09-01 at 14 48 11

It's important that the selector's values should be represented in the url to simplify sharing :)

### PR DESCRIPTION
**Pull request by rajeshj11**
Closes #1770
/claim #1770  

## 📑 Description

Add time frame

## ✅ Checks

- [X] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

demo video:
https://www.loom.com/share/f0f25de12e724e8c97b62d88f25067e5

### CODE REVIEW

**Comment by rajeshj11** [comment]
@Matvey-Kuk @talboren please review

**Comment by Matvey-Kuk** [comment]
Waiting if https://github.com/keephq/keep/issues/1770#issuecomment-2343108059 has a PR before reviewing

**Comment by rajeshj11** [comment]
> Waiting if [#1770 (comment)](https://github.com/keephq/keep/issues/1770#issuecomment-2343108059) has a PR before reviewing

https://github.com/keephq/keep/issues/1770#issuecomment-2360437336
@Matvey-Kuk please review

**Comment by talboren** [comment]
@rajeshj11 please add a loom/screenshots to the description of the PR so we can see that context of the change

**Comment by rajeshj11** [comment]
@Matvey-Kuk @talboren Could you please review? I have added the demo video too.

**Comment by rajeshj11** [comment]
@Matvey-Kuk I just wanted to check in on this PR. When you have time, I'd appreciate your review and any feedback. Let me know if there's anything that needs clarification or further improvement.

Thanks for your time!

**Comment by rajeshj11** [comment]
@talboren I noticed that my pull request has been inactive for some time. If it's no longer needed or doesn’t meet the requirements, please feel free to close it—I completely understand.

**Comment by talboren** [comment]
@rajeshj11 i see that you are waiting for feedback from @Matvey-Kuk, correct?

**Comment by rajeshj11** [comment]
> @rajeshj11 i see that you are waiting for feedback from @Matvey-Kuk, correct?

yes

**Comment by rajeshj11** [comment]
> > @rajeshj11 i see that you are waiting for feedback from @Matvey-Kuk, correct?
> 
>Yes, if someone could provide an update on when I can expect feedback from @Matvey-Kuk, I would appreciate it. If I have a rough estimate of a few days, I won’t need to follow up multiple times.

**Review by Matvey-Kuk — APPROVED** [review]

**Pull request merged**
