### PR TITLE
feat: added microsoft planner provider

### PR DESCRIPTION
**Pull request by Nirali-Ahir**
/attempt #307
/claim #307

fix - #307

Closes # 

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Review by shahargl — CHANGES_REQUESTED** [review]
lgtm just add docs (under docs/) how to use/get the API token

**Comment by shahargl** [comment]
and add the svg

**Comment by Nirali-Ahir** [comment]
added  svg logo and docs

**Review by shahargl — APPROVED** [review]
lgtm

**Pull request merged**
